apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: "/drupal-data"
  accessModes:
    - ReadWriteOnce

# ssh node01
# mkdir /drupal-data
# chmod 777 /drupal-data