apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: "/drupal-mysql-data"
  accessModes:
    - ReadWriteOnce

# ssh node01
# mkdir /drupal-mysql-data
# chmod 777 /drupal-mysql-data