apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
- apiGroups: [""]  
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]  
  resources: ["persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: [""]  
  resources: ["pods"]
  verbs: ["*"]